package aoc2025

import kotlin.test.Test
import kotlin.test.assertEquals

class Day07Test {
    private val input = """
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
    """.trimIndent().lines()

    private val data = Day07.parse(input)

    @Test
    fun `part 1`() {
        assertEquals(21, Day07.solveFirst(data))
    }

    @Test
    fun `part 2`() {
        assertEquals(40, Day07.solveSecond(data))
    }
}
